### ISSUE TITLE
could you help to remove "Indonesia" out of the restriction country list as Indonesia is cleared

### ISSUE THREAD

**Issue by feifeiliibm** [ibm-cloud-docs/Weather#5]
We just got the confirmation from OM George Desrochers that Indonesia is cleared and can be removed from the following restriction list as document in the Cloud Doc (see excerption as below) 

https://cloud.ibm.com/docs/services/Weather?topic=weather-insights_weather_overview&cm_mc_uid=78409233286915657006891&cm_mc_sid_50200000=58912121566974632682

Attention: Currently, the Weather Company Data service may not be purchased or used in the following countries or regions: Afghanistan, Armenia, Azerbaijan, Bahrain, Bangladesh, Bhutan, Brunei, Cambodia, China, Cyprus, Georgia, Indonesia, Iran, Iraq, Japan, Jordan, Kazakhstan, Kuwait, Kyrgyzstan, Laos, Lebanon, Malaysia, Maldives, Mongolia, Myanmar, Nepal, Oman, Pakistan, Philippines, Qatar, Russia, Saudi Arabia, Singapore, South Korea, Sri Lanka, Syria, Tajikistan, Timor-Leste, Turkey, Turkmenistan, United Arab Emirates, Uzbekistan, Vietnam, Yemen. This list is updated when additional information is available.

**Comment by gautammishra** [comment]
@feifeiliibm The content has been updated.
